import Head from "next/head";

import * as React from "react";
import axios from "axios";
import Button from "@mui/material/Button";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import { useTheme } from "@mui/material/styles";
import { Box } from "@mui/material";
import CloseIcon from "@mui/icons-material/Close";

import UploadModalContent from "@/components/UploadModalContent";

export default function Home() {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Skyhop Upload App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Dialog
          maxWidth={"xl"}
          open={true}
          aria-labelledby="responsive-dialog-title"
          PaperProps={{
            sx: {
              borderRadius: "20px",
              padding: 2,
              width: "900px",
            },
          }}
        >
          <CloseIcon
            style={{
              color: "white",
              backgroundColor: "#061346",
              margin: 10,
              padding: 4,
              borderRadius: 7,
              position: "absolute",
            }}
          />

          <DialogTitle
            id="responsive-dialog-title"
            sx={{ textAlign: "center", marginBottom: -2.5 }}
          >
            <Box
              component={"div"}
              style={{
                fontSize: "28px",
                fontWeight: 800,
                borderBottom: "1px solid lightgrey",
                paddingBottom: 7,
                paddingTop: 25,
                display: "inline-block",
              }}
            >
              Document Upload
            </Box>
          </DialogTitle>
          <DialogContent>
            <UploadModalContent />
          </DialogContent>
          <DialogActions
            sx={{
              display: "flex",
              justifyContent: "center",
              marginTop: -5,
              marginBottom: 3.5,
            }}
          >
            <Button
              sx={{
                paddingY: 1,
                borderRadius: 1.5,
              }}
              variant="contained"
              style={{
                width: 200,
                boxShadow: "none",
                backgroundColor: "#172D5B",
                textTransform: "none",
                fontSize: 12,
              }}
            >
              Continue Import
            </Button>
            <Button
              sx={{
                paddingY: 1,
                borderRadius: 1.5,
              }}
              variant="outlined"
              style={{
                width: 200,
                boxShadow: "none",
                textTransform: "none",
                fontSize: 12,
                color: "#F78B1E",
                borderColor: "#F78B1E",
                borderWidth: 2,
              }}
            >
              Cancel
            </Button>
          </DialogActions>
        </Dialog>
      </>
    </>
  );
}
